export const SECTION_CASE_MAPPING: Record<string, string[]> = {
  "0": ["lvl-3", "daily-free", "bonus-case"],
  "1": ["summer-event", "winter-special"],
  "2": ["bestseller-1", "popular-choice", "top-rated"],
  "3": ["community-vote", "player-favorite"],
  "4": ["discord-exclusive", "server-boost"],
  "5": ["armory-bundle-1", "weapon-pack"],
  "6": ["color-mania", "rainbow-case"],
  "7": ["vitality-pro", "team-vitality"],
  "8": ["crazy-deal-1", "flash-sale"],
  "9": ["anime-case-1", "manga-special"],
  "10": ["battle-arena", "pvp-case"],
  "11": ["sticker-pack-1", "decal-collection"],
  "12": ["farm-case-1", "all-nothing"],
  "13": ["vault-case-1", "collection-rare"],
  "14": ["special-daily", "giveaway-case"],
  "15": ["mil-spec", "classified", "covert"],
  "16": ["awp-cases", "ak47-cases", "m4a4-cases"],
  "17": ["exclusive-1", "unique-design"],
  "18": ["creator-case-1", "youtuber-pick"],
  "19": ["karrigan-pick", "pro-choice"],
  "20": ["classic-case-1", "retro-style"],
  "21": ["map-collection", "dust2-case"],
};
