export const SECTION_CASE_MAPPING: Record<string, string[]> = {
  "0": [
    "lvl-3",
    "lvl-10",
    "lvl-20",
    "lvl-30",
    "lvl-40",
    "lvl-50",
    "lvl-60",
    "lvl-70",
    "lvl-80",
    "lvl-90",
    "lvl-100",
    "lvl-110",
    "lvl-120",
  ],
  "1": ["cowboy", "bat-bridge", "south-neon", "live-frag", "moody-center"],
  "2": ["new-to-town", "electric-dreams", "canon-event", "steel-samurai", "galactic-phases"],
  "3": [],
  "4": ["stork", "chimpanzini-bananini", "tiger", "snake", "photoroom"],
  "5": ["small-arms", "missing-link", "graphic", "crakow-monster", "sport-and-field"],
  "6": ["amberglow", "green-glimmer", "violet-veil", "redwood-bash", "lazuli-abyss"],
  "7": ["sniper", "lurker", "anchor", "rifler", "igl"],
  "8": ["demon-step", "trinity-force", "royalty", "guardian-of-wilderness", "who-is-crazy"],
  "9": ["devils-footprint", "pirate-king", "turbo-okarun", "warden-of-the-abyss", "the-honored-one"],
  "10": [
    "the-rivalry",
    "ak47-battle",
    "awp-battle",
    "balance-battle",
    "mid",
    "mystic-hundred",
    "convert-battle",
    "monsters-paradise",
    "gloves-combat",
    "gloves-battle",
    "top-battle",
  ],
  "11": [
    "big-chicken",
    "kawaii",
    "majors-legends",
    "scratcher",
    "meme-party",
    "riddler",
    "new-gen-top",
    "it-moves",
    "holo-mania",
    "dual-gleam",
    "big-legends",
  ],
  "12": [
    "farm-zeus",
    "farm-m4",
    "farm-ak47",
    "farm-awp",
    "farm-ct-pistols",
    "farm-t-pistols",
    "farm-desert-eagle",
    "farm-knives",
    "farm-phase",
    "farm-gloves",
  ],
  "13": ["ascent", "boreal", "radiant", "trainline"],
  "14": [],
  "15": ["milspec", "restricted", "classified", "covert", "knife"],
  "16": [
    "aug",
    "sg553",
    "glock18",
    "p90",
    "usp-s",
    "m4a4",
    "desert-eagle",
    "ak47",
    "m4a1-s",
    "awp",
    "survival-knives",
    "kukri-knives",
    "skeleton-knives",
    "flip-knives",
    "butterfly-knives",
    "m9-bayonet-knives",
    "karambit-knives",
  ],
  "17": [
    "full-flash",
    "pickle-world",
    "arena",
    "anti-rush",
    "dream",
    "half-life",
    "rainbow",
    "sunny-set",
    "4-pro",
    "sc-fun",
    "nightmare",
    "team-vitality",
    "bloody",
    "its-a-palworld",
    "sands-of-anubis",
    "ak-blues",
    "hot",
    "exotic",
    "bloody-asiimov",
    "fire-and-water",
    "agents",
    "ace-clutch",
    "source2-exe",
    "honey",
    "stattrak",
    "asiimov",
    "sc-pro",
    "the-mongolz",
    "monster",
    "purple-rain",
    "ultraviolet-case",
    "silver-bull",
    "25-anniversary",
    "factory-new",
    "convert-knife",
    "pro-investor",
    "hanami",
    "piece-of-luck",
    "sc-god",
    "winner-set",
    "glover",
    "exclusive",
    "star-pearl",
    "this-is-a-major",
    "maelstrom",
    "lady-luck",
    "overtimes",
    "diamond-skins",
    "gloves",
    "the-legendary-howls",
    "fantastic",
    "maze-trip",
  ],
  "18": [
    "znorux",
    "toby-on-the-tele",
    "superstitum",
    "cej0t",
    "d4x",
    "ag1l",
    "joispoi24",
    "kaeryka",
    "franzj",
    "mutiris",
    "hai-x",
    "azuwu",
    "angvil",
    "molto-niico",
    "story",
    "karrigans-choice",
    "peacemaker",
    "sparkles",
    "ricky",
    "mateoz",
  ],
  "19": ["cs-1-6-memories", "cobblestone-1v4", "hltv-confirmed", "major-legend", "eco-rush-b"],
  "20": [
    "shadow",
    "operation-breakout-weapon",
    "glove",
    "fracture",
    "prisma",
    "chroma",
    "chroma-3",
    "dreams-and-nightmares",
    "recoil",
    "danger-zone",
    "gamma",
    "fever",
    "spectrum-2",
    "revolution",
    "operation-phoenix-weapon",
    "snakebite",
    "gamma-2",
    "cs20-case",
    "esports-2013-winter",
    "horizon",
    "shattered-web",
    "broken-fang",
    "huntsman-weapon",
    "spectrum",
    "clutch",
    "chroma-2",
    "prisma-2",
    "esports-2013",
    "Hydra",
    "operation-bravo",
    "weapon",
  ],
  "21": [
    "2021-mirage",
    "2021-vertigo",
    "inferno",
    "2021-dust-2",
    "anubis",
    "havoc",
    "chop-shop",
    "canals",
    "cobblestone",
    "nuke",
    "control",
    "ancient",
    "norse",
    "office",
    "dust",
  ],
};
