import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import TopUpModal from "./components/modals/TopUpModal";
import HeaderMenu from "./components/HeaderMenu";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Skam.Club",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <TopUpModal />
      <body className={inter.className}>
        <HeaderMenu />
        {children}
      </body>
    </html>
  );
}
